### ISSUE TITLE
Is a pity that only for mysql

### ISSUE THREAD

**Issue by Insolita** [Beaten-Sect0r/yii2-db-manager#1]
:(

**Comment by Beaten-Sect0r** [comment]
добавил postgresql
https://github.com/Beaten-Sect0r/yii2-db-manager/commit/48a8ba7790226e30dfeadb37e3028f2917c42c03

**Comment by Insolita** [comment]
Так не работает  https://github.com/Beaten-Sect0r/yii2-db-manager/blob/master/controllers/DefaultController.php#L62
` 
  $command = 'PGPASSWORD='.$this->module->password.' pg_dump --host=' . $this->module->host . ' --username=' . $this->module->username . ' --no-password ' . $this->module->dbName . ' > '.$dump ;
`

**Comment by Beaten-Sect0r** [comment]
Спасибо!

**Comment by Insolita** [comment]
У тебя однако автообновление на packagist.org не срабатывает https://packagist.org/packages/beaten-sect0r/yii2-db-manager на старый коммит указывает.

**Comment by Beaten-Sect0r** [comment]
Странно, работало, настроил заново.

**Comment by Insolita** [comment]
Ну вроде ок, ты раз скрин сделал - значит тоже работает. 
А для винды кому надо - может написать свои DumpManager и подставить их в настройки модуля. У мну нет винды и нет ни малейшего желания её совать,поэтому с ней ничем не могу помочь

**Comment by Beaten-Sect0r** [comment]
В windows работает, в виндовс нельзя использовать ":" в имени файла.

**Comment by Beaten-Sect0r** [comment]
Так у Вас работает?
https://github.com/Beaten-Sect0r/yii2-db-manager/blob/master/models/PostgresDumpManager.php#L21

**Comment by Insolita** [comment]
не будет так работать
http://linux.die.net/man/1/pg_dump
там опция --password это принудительый запрос пароля и параметра она не принимает, верни как было. 

https://git-scm.com/book/ru/ch2-6.html

**Comment by Beaten-Sect0r** [comment]
Был ключ --user, в мане --username.

**Comment by Insolita** [comment]
https://github.com/Beaten-Sect0r/yii2-db-manager/blob/master/models/PostgresDumpManager.php#L63
тут password тоже убрать надо, --no-password вернуть

**Comment by Beaten-Sect0r** [comment]
Да, я заметил уже.
Так пойдёт?

**Comment by Insolita** [comment]
по сути - да, по факту лучше сделать метод типа 

```
public function isWindows()
{
      return strtoupper(substr(PHP_OS, 0, 3)) === 'WIN'
} 
```

и вынести его в BaseDumpManager
а в наследниках проверять 

```
        if ($this->isWindows()) 
       {
              //....
       }
```

**Comment by Beaten-Sect0r** [comment]
Спасибо, готово.

**Comment by Insolita** [comment]
ну вроде норм. поставь метку.
