### ISSUE TITLE
problem with db password

### ISSUE THREAD

**Issue by ekawalec** [Beaten-Sect0r/yii2-db-manager#12]
There is a problem with db passwords like 4iN8@Ud71&EToWEF - it contains characters: @ & and dump failed :(  
All passwords in command:
PGPASSWORD='4iN8@Ud71&EToWEF' pg_dump --host= 
needs to be in inverted commas

**Comment by Beaten-Sect0r** [comment]
Thanks!

**Comment by ekawalec** [comment]
No problem, quick reaction!!!
