### ISSUE TITLE
PHP Warning 'yii\base\ErrorException' with message 'fwrite() expects parameter 2 to be string, resource given'

### ISSUE THREAD

**Issue by ignatenkovnikita** [Beaten-Sect0r/yii2-db-manager#14]
Нашел возникновние ошибки и заменил на 78 строке 
с 
`
$dumpText = fopen($dumpPath, 'r');
Yii::$app->backupStorage->write(StringHelper::basename($dumpPath), $dumpText);
fclose($dumpText);
`
на 
`
$dumpText = fopen($dumpPath, 'r+');
Yii::$app->backupStorage->writeStream(StringHelper::basename($dumpPath), $dumpText);
fclose($dumpText);
`

**Comment by Beaten-Sect0r** [comment]
Спасибо!
