### ISSUE TITLE
PHP Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by kwazaro** [Beaten-Sect0r/yii2-db-manager#24]
Db Manager admin page throws this

**Comment by Beaten-Sect0r** [comment]
https://github.com/Beaten-Sect0r/yii2-db-manager/search?q=count&unscoped_q=count

**Comment by Beaten-Sect0r** [comment]
Where does this happen?

**Comment by kwazaro** [comment]
DefaultController

**Comment by Beaten-Sect0r** [comment]
а строка какая? Копируйте ошибку полностью пожалуйста.

**Comment by kwazaro** [comment]
Ошибка возникает, когда открывается дефолтный контроллер, и список бекапов (директория бекапов) пуст. Версия PHP 7.2. Там длинный Trace, Начинается с ошибки ArrayDataProvider. Видимо, ему не нравится то, что он получает, если файлов в папке нет. (в новых версиях PHP есть слом обратной совместимости для функции count()).

**Comment by kwazaro** [comment]
Я PR сделаю

**Comment by Beaten-Sect0r** [comment]
Спасибо!
