### ISSUE TITLE
Empty database file created

### ISSUE THREAD

**Issue by iammuhammadumair** [Beaten-Sect0r/yii2-db-manager#28]
Hello, my sql file is empty i am using following config:
i am using my alias from bootstrap.php
`Yii::setAlias('@backup', dirname(dirname(__DIR__)) . '/backup');`

in config/main.php
```
'modules' => [
        'db-manager' => [
            'class' => 'bs\dbManager\Module',
            'path' => '@backup',
            'dbList' => ['db'],
            'as access' => [
                'class' => 'yii\filters\AccessControl',
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ],
```

in console config
```
'modules' => [
        'db-manager' => [
            'class' => 'bs\dbManager\Module',
            // path to directory for the dumps
            'path' => '@backup',
            // list of registerd db-components
            'dbList' => ['db'],
        ],
    ],
```

i am getting result :
>**php yii dump/create -db=db -gz -s**
Storage component is not configured.
Dump successfully created.

gzip file is created but with 0b size

**Comment by iammuhammadumair** [comment]
mysqldump and gzip are installed and configured properly

**Comment by rlpaas** [comment]
same as mine empty why?

**Comment by AgusWijiSuhariono** [comment]
Same as mine, why i get empty dump database

**Comment by gogl92** [comment]
I think the problem is that the extension needs for `creocoder\flysystem\LocalFilesystem` to be installed and configured when it should be used in any class which extends from flysystem.

Check:

https://github.com/Beaten-Sect0r/yii2-db-manager/blob/a9fc346b7fa65d2deabb0e1aaa92206bd2b732a6/src/commands/DumpController.php#L104
