### ISSUE TITLE
custom timeout on dump/create

### ISSUE THREAD

**Issue by carlosbispo** [Beaten-Sect0r/yii2-db-manager#29]
I have a large database that takes more than 60 seconds to backup.
Is it possible to add custom timeout to prevent this to happen?
For now i have to edit manualy DumpController.php to change this...
Offending line : 73 version: 2.2.1.
By the way: great job!

**Comment by Beaten-Sect0r** [comment]
Thank! So good? https://github.com/Beaten-Sect0r/yii2-db-manager#advanced-config

**Comment by Beaten-Sect0r** [comment]
```
            // Process timeout
            'timeout' => 3600,
```
