### ISSUE TITLE
gZip сжатие - пустой файл

### ISSUE THREAD

**Issue by Blacknife** [Beaten-Sect0r/yii2-db-manager#4]
День добрый! Модуль прекрасно работает, но при выборе опции gZip сжатия сохраняется пустой файл, в чём может быть проблема?

**Comment by Beaten-Sect0r** [comment]
Привет!
Если в консоль отправить команду gzip - работает?
gzip установлен?

**Comment by Blacknife** [comment]
Прошу прощения, разобрался, проблема оказалась только на локальной машине! В любом случае спасибо!

**Comment by Beaten-Sect0r** [comment]
Пожалуйста.
