### ISSUE TITLE
Dump failed

### ISSUE THREAD

**Issue by vc7deo** [Beaten-Sect0r/yii2-db-manager#9]
Dump failed.
Command - mysqldump --host=localhost --port=3306 --user=root --password= --no-data advoapp | gzip > C:\wamp\www\advoapp/backend/backups/advoapp_schema_default_2017-06-16_06-13-53.sql.gz
'mysqldump' is not recognized as an internal or external command, operable program or batch file.

![image](https://user-images.githubusercontent.com/8149102/27214738-91bcd646-528b-11e7-8496-3f67626bf39b.png)

**Comment by Beaten-Sect0r** [comment]
Hi. Add mysqldump and gzip (http://gnuwin32.sourceforge.net/downlinks/gzip-bin-zip.php) to windows path.
https://www.google.com/search?q=add+to+windows+path&oq=add+to+windows+path
